
/*File generated by maple/csh_fast.mw*/

/* some constants for the hyperbolic sine and the hyperbolic cosine */ 
#ifdef WORDS_BIGENDIAN  
  db_number const max_inf_input_ch = {{0x408633CE,0x8FB9F87E}};     /*7.1047586007e+02*/  
  db_number const max_input_ch = {{0x404BB9D3,0xBEB8C86B}};     /*5.5451774445e+01*/  
  db_number const min_inf_input_ch = {{0xC08633CE,0x8FB9F87E}};     /*-7.1047586007e+02*/  
  db_number const min_input_ch = {{0xC08633CE,0x8FB9F87E}};     /*-7.1047586007e+02*/  
  db_number const min_absolute_input_ch = {{0x3E400000,0x00000000}};     /*7.4505805969e-09*/  
  db_number const max_inf_input_exp = {{0x40862E42,0xFEFA39EF}};     /*7.0978271289e+02*/  
  db_number const max_inf_input_sh = {{0x408633CE,0x8FB9F87E}};     /*7.1047586007e+02*/  
  db_number const max_input_sh = {{0x404BB9D3,0xBEB8C86B}};     /*5.5451774445e+01*/  
  db_number const min_inf_input_sh = {{0x408633CE,0x8FB9F87E}};     /*7.1047586007e+02*/  
  db_number const min_input_sh = {{0xC04BB9D3,0xBEB8C86B}};     /*-5.5451774445e+01*/  
  db_number const min_absolute_input_sh = {{0x3E500000,0x00000000}};     /*1.4901161194e-08*/  
  db_number const inv_ln_2 =   {{0x3FF71547,0x652B82FE}};     /*1.4426950409e+00*/  
  db_number const ln2_hi = {{0x3FE62E42,0xFEFA3800}};     /*6.9314718056e-01*/  
  db_number const ln2_lo = {{0x3D2EF357,0x93C76730}};     /*5.4979230187e-14*/  
/* the coefficients for the cosh-approximations */ 
  db_number const c0_hi =   {{0x3FF00000,0x00000000}};     /*1.0000000000e+00*/  
  db_number const c0_lo =   {{0x00000000,0x00000000}};     /*0.0000000000e+00*/  
  db_number const c1_hi =   {{0x3FE00000,0x00000000}};     /*5.0000000000e-01*/  
  db_number const c1_lo =   {{0x00000000,0x00000000}};     /*0.0000000000e+00*/  
  db_number const c0 =   {{0x3FF00000,0x00000000}};     /*1.0000000000e+00*/  
  db_number const c1 =   {{0x3FE00000,0x00000000}};     /*5.0000000000e-01*/  
  db_number const c2 =   {{0x3FA55555,0x55555555}};     /*4.1666666667e-02*/  
  db_number const c3 =   {{0x3F56C16C,0x16C16C17}};     /*1.3888888889e-03*/  
  db_number const c4 =   {{0x3EFA01A0,0x1A01A01A}};     /*2.4801587302e-05*/  
  db_number const c5 =   {{0x3E927E4F,0xB7789F5C}};     /*2.7557319224e-07*/  
  db_number const c6 =   {{0x3E21EED8,0xEFF8D898}};     /*2.0876756988e-09*/  
  db_number const c7 =   {{0x3DA93974,0xA8C07C9D}};     /*1.1470745598e-11*/  
/* the coefficients for the sinh-approximations */
  db_number const s0_hi =   {{0x3FF00000,0x00000000}};     /*1.0000000000e+00*/  
  db_number const s0_lo =   {{0x00000000,0x00000000}};     /*0.0000000000e+00*/  
  db_number const s1_hi =   {{0x3FC55555,0x55555555}};     /*1.6666666667e-01*/  
  db_number const s1_lo =   {{0x3C655555,0x55555555}};     /*9.2518585385e-18*/  
  db_number const s0 =   {{0x3FF00000,0x00000000}};     /*1.0000000000e+00*/  
  db_number const s1 =   {{0x3FC55555,0x55555555}};     /*1.6666666667e-01*/  
  db_number const s2 =   {{0x3F811111,0x11111111}};     /*8.3333333333e-03*/  
  db_number const s3 =   {{0x3F2A01A0,0x1A01A01A}};     /*1.9841269841e-04*/  
  db_number const s4 =   {{0x3EC71DE3,0xA556C734}};     /*2.7557319224e-06*/  
  db_number const s5 =   {{0x3E5AE645,0x67F544E4}};     /*2.5052108385e-08*/  
  db_number const s6 =   {{0x3DE61246,0x13A86D09}};     /*1.6059043837e-10*/  
#else  
  db_number const max_inf_input_ch = {{0x8FB9F87E,0x408633CE}};     /*7.1047586007e+02*/  
  db_number const max_input_ch = {{0xBEB8C86B,0x404BB9D3}};     /*5.5451774445e+01*/  
  db_number const min_inf_input_ch = {{0x8FB9F87E,0xC08633CE}};     /*-7.1047586007e+02*/  
  db_number const min_input_ch = {{0x8FB9F87E,0xC08633CE}};     /*-7.1047586007e+02*/  
  db_number const min_absolute_input_ch = {{0x00000000,0x3E400000}};     /*7.4505805969e-09*/  
  db_number const max_inf_input_sh = {{0x8FB9F87E,0x408633CE}};     /*7.1047586007e+02*/  
  db_number const max_input_sh = {{0xBEB8C86B,0x404BB9D3}};     /*5.5451774445e+01*/  
  db_number const min_inf_input_sh = {{0x8FB9F87E,0x408633CE}};     /*7.1047586007e+02*/  
  db_number const min_input_sh = {{0xBEB8C86B,0xC04BB9D3}};     /*-5.5451774445e+01*/  
  db_number const min_absolute_input_sh = {{0x00000000,0x3E500000}};     /*1.4901161194e-08*/  
  db_number const max_inf_input_exp = {{0xFEFA39EF,0x40862E42}};     /*7.0978271289e+02*/  
  db_number const inv_ln_2 =   {{0x652B82FE,0x3FF71547}};     /*1.4426950409e+00*/  
  db_number const ln2_hi = {{0xFEFA3800,0x3FE62E42}};     /*6.9314718056e-01*/  
  db_number const ln2_lo = {{0x93C76730,0x3D2EF357}};     /*5.4979230187e-14*/  
/* the coefficients for the cosh-approximations */ 
  db_number const c0_hi =   {{0x00000000,0x3FF00000}};     /*1.0000000000e+00*/  
  db_number const c0_lo =   {{0x00000000,0x00000000}};     /*0.0000000000e+00*/  
  db_number const c1_hi =   {{0x00000000,0x3FE00000}};     /*5.0000000000e-01*/  
  db_number const c1_lo =   {{0x00000000,0x00000000}};     /*0.0000000000e+00*/  
  db_number const c0 =   {{0x00000000,0x3FF00000}};     /*1.0000000000e+00*/  
  db_number const c1 =   {{0x00000000,0x3FE00000}};     /*5.0000000000e-01*/  
  db_number const c2 =   {{0x55555555,0x3FA55555}};     /*4.1666666667e-02*/  
  db_number const c3 =   {{0x16C16C17,0x3F56C16C}};     /*1.3888888889e-03*/  
  db_number const c4 =   {{0x1A01A01A,0x3EFA01A0}};     /*2.4801587302e-05*/  
  db_number const c5 =   {{0xB7789F5C,0x3E927E4F}};     /*2.7557319224e-07*/  
  db_number const c6 =   {{0xEFF8D898,0x3E21EED8}};     /*2.0876756988e-09*/  
  db_number const c7 =   {{0xA8C07C9D,0x3DA93974}};     /*1.1470745598e-11*/  
/* the coefficients for the sinh-approximations */
  db_number const s0_hi =   {{0x00000000,0x3FF00000}};     /*1.0000000000e+00*/  
  db_number const s0_lo =   {{0x00000000,0x00000000}};     /*0.0000000000e+00*/  
  db_number const s1_hi =   {{0x55555555,0x3FC55555}};     /*1.6666666667e-01*/  
  db_number const s1_lo =   {{0x55555555,0x3C655555}};     /*9.2518585385e-18*/  
  db_number const s0 =   {{0x00000000,0x3FF00000}};     /*1.0000000000e+00*/  
  db_number const s1 =   {{0x55555555,0x3FC55555}};     /*1.6666666667e-01*/  
  db_number const s2 =   {{0x11111111,0x3F811111}};     /*8.3333333333e-03*/  
  db_number const s3 =   {{0x1A01A01A,0x3F2A01A0}};     /*1.9841269841e-04*/  
  db_number const s4 =   {{0xA556C734,0x3EC71DE3}};     /*2.7557319224e-06*/  
  db_number const s5 =   {{0x67F544E4,0x3E5AE645}};     /*2.5052108385e-08*/  
  db_number const s6 =   {{0x13A86D09,0x3DE61246}};     /*1.6059043837e-10*/  
#endif  
